version: "3.8"
services:
    node:
        image: node:latest
        volumes:
            - ./server:/usr/local/app
        environment:
            DATABASE_URL: ${DATABASE_URL:-postgres://root:password@database:5432/app}
            PORT: ${PORT:-8080}
        working_dir: /usr/local/app
        ports:
            - 127.0.0.1:8080:8080
        command: npm run dev
        env_file:
            - .env
        depends_on:
            - database
        restart: always

    database:
        image: postgres:latest
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: app
        healthcheck:
            test: ["CMD-SHELL", "pg_isready", "-h", "localhost", "-p","5432","-U","root"]
            interval: 10s
            timeout: 5s
            retries: 3

    adminer:
        image: adminer:latest
        ports:
            - 8081:8080
        restart: always
        depends_on:
            - database

volumes:
    postgres-data: {}